export const THEMES = {
  LIGHT: 'light',
  DARK: 'dark',
};

export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SWITCH_THEME = 'SWITCH_THEME';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';

export const SET_IS_AUTHENTICATING = 'SET_IS_AUTHENTICATING';
export const SET_AUTHENTICATION_ERROR = 'SET_AUTHENTICATION_ERROR';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
